### PR TITLE
use CG-DRAFT template

### PR DESCRIPTION
**Pull request by elf-pavlik**
Previews:

* https://elf-pavlik.github.io/notifications/streaming-http-channel-2023
* https://elf-pavlik.github.io/notifications/webhook-channel-2023
* https://elf-pavlik.github.io/notifications/webpush-subscription-2022

BTW: Later this week, I plan to PR WebPushChannel2023 since I have been implementing it lately.

### CODE REVIEW

**Comment by CxRes** [comment]
Per the CG discussion (which I colossally disagree with), we need to remove the W3C logo as well. :(

**Comment by elf-pavlik** [comment]
This is a misunderstanding; I'm using a standard CG-DRAFT template. I will ask about it in the issue with participation from W3C.

**Review by csarven — CHANGES_REQUESTED** [review]
Make sure that the copyright and SotD conforms to https://www.w3.org/community/reports/reqs/

**Comment by elf-pavlik** [comment]
This will be resolved soon, tracking it in https://github.com/solid/specification/issues/587#issuecomment-2174595176

**Comment by elf-pavlik** [comment]
okie dokie, this one is ready!

**Review by csarven — APPROVED** [review]
I don't have the environment setup to test this but assuming it works, and if you find it useful for yourself and conforms to whatever W3C needs, great.

**Pull request merged**
